#
# Ref: https://www.appveyor.com/docs/appveyor-yml/
#
version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2019
configuration: Release
platform: x64
clone_folder: c:\projects\pwn++
build:
  project: .\pwn++.sln
  verbosity: normal
