# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master


variables:
  solution: 'pwn++.sln'
  buildPlatform: 'x86|x64'
  buildConfiguration: 'Release'


resources:
  repositories:
  - repository: capstone
    type: github
    name: aquynh/capstone
    endpoint: hugsy
  - repository: keystone
    type: github
    name: keystone-engine/keystone
    endpoint: hugsy
 
jobs:
- job: 'build_pwnlib_win10'
  pool:
    vmImage: 'windows-2019'
  steps:
  - checkout: self
  - checkout: capstone


  - task: CmdLine@2
    displayName: 'Prepare Capstone build'
    inputs:
      targetType: 'inline'
      script: "echo foo"
      workingDirectory: capstone\msvc
      
  - task: VSBuild@1
    displayName: 'Build Capstone'
    inputs: 
      configuration: 'Release'
      platform: 'x64'
      solution: capstone\msvc\capstone.sln
      
      
  - task: MSBuild@1
    displayName: 'Build Pwn++'
    inputs: 
      msbuildArguments: '-nologo /m /p:Configuration=Release'
      solution: $(solution)
  - task: PublishBuildArtifacts@1
    condition: ne(variables['Build.Reason'], 'PullRequest')
    inputs:
      pathtoPublish: './build'
      artifactName: win64build
