name: CI Build for MSVC

on: 
  push:
    branches:
      - master

env:
  BUILD_TYPE: Release


jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]
    
    steps:
    
    - uses: actions/checkout@v2

    - name: Upgrade Capstone lib
      working-directory:  libs\capstone\msvc\
      shell: cmd
      run: |
        C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat
        devenv.exe /resetsettings
        devenv.exe capstone.sln /upgrade

    - name: Build Capstone lib
      working-directory:  libs\capstone\msvc\
      shell: cmd
      run: |
        C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat
        msbuild.exe capstone.sln -nologo /m /p:Configuration=$ENV{BUILD_TYPE}


    - name: Compile pwn++ DLL
      shell: cmd
      run: |
        msbuild.exe pwn++.sln -nologo /m /p:Configuration=$ENV{BUILD_TYPE}
