name: CI Build for MSVC

on: 
  push:
    branches:
      - master

env:
  BUILD_TYPE: Release


jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
        - {
            name: "Windows Latest MSVC x64", 
            artifact: "Windows-msvc-x64.tar.xz",
            os: windows-latest,
            cc: "cl", cxx: "cl",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }


    steps:
    - name: Checkout
      uses: actions/checkout@v2
   
    - name: Upgrade Capstone lib
      shell: cmd
      run: |       
        cd libs\
        git clone https://github.com/aquynh/capstone.git
        cd capstone\msvc
        devenv.exe capstone.sln /upgrade

    - name: Build Capstone lib
      shell: cmd
      run: |
        cd libs\capstone\msvc
        msbuild.exe capstone.sln -nologo /m /p:Configuration=$ENV{BUILD_TYPE}


    - name: Compile pwn++ DLL
      shell: cmd
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        msbuild.exe pwn++.sln -nologo /m /p:Configuration=$ENV{BUILD_TYPE}
