name: CI Build for MSVC

on: 
  push:
    branches:
      - master

env:
  BUILD_TYPE: Release


jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows Latest MSVC", artifact: "Windows-MSVC.tar.xz",
            os: windows-latest,
            cc: "cl", cxx: "cl",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }
    
    steps:
    
    - uses: actions/checkout@v2

    - uses: actions/checkout@v2
      with:
        repository: aquynh/capstone

    - name: Upgrade Capstone lib
      working-directory:  libs\
      shell: |
        devenv.exe /resetsettings
        devenv.exe capstone.sln /upgrade

    - name: Build Capstone lib
      working-directory:  libs\
      shell: |
        msbuild.exe capstone\msvc\capstone.sln





    - name: Compile pwn++ DLL
      shell: |
        msbuild.exe pwn++.sln -nologo /m /p:Configuration=$ENV{BUILD_TYPE}