name: CI Build for MSVC

on: 
  push:
    branches:
      - master

jobs:
  build:
    name: "Building pwn++"
    runs-on: [windows-latest]
    strategy:
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true
   
    - name: Build Capstone lib
      shell: pwsh
      run: |
        cd libs\capstone\msvc
        Import-Module .\ci\Invoke-VS.ps1
        Invoke-VisualStudio2019x64
        devenv capstone.sln -nologo /resetsettings
        devenv capstone.sln -nologo /upgrade
        msbuild capstone_static/capstone_static.vcxproj -m -nologo /p:Configuration="Release"
      
      
    - name: Build Keystone lib
      shell: pwsh
      run: |
        Import-Module .\ci\Invoke-VS.ps1
        Invoke-VisualStudio2019x64
        mkdir libs\keystone\build
        cd libs\keystone\build
        ..\nmake-lib.bat
#        devenv keystone.sln -nologo /upgrade
#        msbuild keystone.sln -m -nologo /p:Configuration="Release"

    - name: Build pwn++ DLL
      shell: cmd
      run: |
        Import-Module .\ci\Invoke-VS.ps1
        Invoke-VisualStudio2019x64
        msbuild pwn++.sln -nologo /m /p:Configuration="Release"
