name: CI Build for MSVC

on: 
  push:
    branches:
      - master

jobs:
  build:
    name: "Building pwn++"
    runs-on: [windows-latest]
    strategy:
      fail-fast: false

    steps:
    - name: Build Capstone lib
      uses: actions/checkout@v2
      with:
         repository: 'aquynh/capstone'
   
    - name: Build Capstone lib
      shell: pwsh
      run: |
        Import-Module .\.ci\Invoke-VS.ps1
        cd ..
        git clone https://github.com/aquynh/capstone
        cd .\capstone\msvc
        Invoke-VisualStudio2019x64
        devenv capstone.sln -nologo /resetsettings
        devenv capstone.sln -nologo /upgrade
        msbuild capstone_static/capstone_static.vcxproj -m -nologo /p:Configuration="Release" /p:Platform=x64


    - name: Clone Keystone lib
      uses: actions/checkout@v2
      with:
         repository: 'keystone-engine/keystone'

    - name: Build Keystone lib
      shell: pwsh
      run: |
        Import-Module .\.ci\Invoke-VS.ps1
        cd ..
        git clone https://github.com/keystone-engine/keystone
        Invoke-VisualStudio2019x64
        mkdir .\keystone\build
        cd .\keystone\build
        ..\nmake-lib.bat
          

    - uses: actions/checkout@v2
      
    - name: Build pwn++ DLL
      shell: pwsh
      run: |
        Import-Module .\.ci\Invoke-VS.ps1
        New-Item -ItemType SymbolicLink -Target "..\pwn--" -Path "..\pwn++" -ErrorAction Continue
        Invoke-VisualStudio2019x64
        msbuild pwn++\pwn++.vcxproj -nologo /m /p:Configuration=Release /p:Platform=x64


    - name: Prepare artifact
      id: prepare_artifact
      shell: pwsh
      run: |
        mkdir build\
        cp pwn++\x64\Release\pwn++.dll build\
        cp pwn++\x64\Release\pwn++.pdb build\
        cp pwn++\x64\Release\pwn++.lib build\
        mkdir build\include\
        cp pwn++\*.h build\include\
        
    - name: Publish artifact
      id: publish_artifact
      uses: actions/upload-artifact@v2
      with:
        name: latest build
        path: build\
